### PR TITLE
Show Chart axis when selected on none

### LINKED ISSUE #607: Try and show chart axis even if all items are disabled
We previously stopped users from de-selecting all items in a graph, but it's now possible with the new select all/none legend controls on certain graphs. Can lead to broken looking panels.

Big white space left where the graph would be,  example from a mobile layout (better than the space collapsing in, worse than there still being something there):
image

Probably a fair bit of work, potentially hacking around how nivo works. Might be able to make it more straightforward to achieve this in the process of doing #599, if I plan for it while standardizing the wrapped nivo component APIs.

### PR DESCRIPTION
**Pull request by GarvinH**
closes #607 

image

image

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
Did you look in to disabling tooltips while in none mode? Right now, there's a tooltip for the hidden line, which will be pretty confusing for users (they'll think it is a bug, which makes it a bug).

**Comment by GarvinH** [comment]
Whoops I forgot to remove that earlier. Thanks!

File: client/src/panels/panel_declarations/finances/sobj/spend_by_so_hist.js [hunk 1]
```diff
@@ -87,6 +95,66 @@ class SobjLine extends React.Component {
         .value(),
     };
 
+    const get_line_graph = (() => {
+      if (_.isEmpty(spending_data) && _.isEmpty(raw_data)) {
+        const max_y = _.max(_.map(data, (obj) => _.max(obj.data)));
```
Comment (ktw1016) [inline client/src/panels/panel_declarations/finances/sobj/spend_by_so_hist.js:100]: I think this would be cleaner in a chain like this:
```       
 _.chain(data)
  .map((row) => _.max(row.data))
  .max()
  .value()
```

File: client/src/panels/panel_declarations/finances/sobj/spend_by_so_hist.js [hunk 2]
```diff
@@ -87,6 +95,66 @@ class SobjLine extends React.Component {
         .value(),
     };
 
+    const get_line_graph = (() => {
+      if (_.isEmpty(spending_data) && _.isEmpty(raw_data)) {
```
Comment (ktw1016) [inline client/src/panels/panel_declarations/finances/sobj/spend_by_so_hist.js:99]: Hmm, how about having one variable as Nivo props so that you can get rid of redundant props passing and if statements? This would go for same on other files

```
const is_data_empty = _.isEmpty(spending_data) && _.isEmpty(raw_data);
const empty_data_nivo_props = is_data_empty && { // props that are only for empty data
data: ...,
raw_data: ....
enableDots: ...,
},
const nivo_props = { // props for both regular data and empty data
data: ...,
raw_data:...,
margin:...,
graph_height:...,
...empty_data_nivo_props,
}
```
and then straight in render function,
`<NivoResponsiveLine {...nivo_props} />`

File: client/src/panels/panel_declarations/finances/transfer_payments/historical_g_and_c.js [hunk 3]
```diff
@@ -192,25 +192,39 @@ class DetailedHistTPItems extends React.Component {
       .fromPairs()
       .value();
 
+    const max_value = _.max(
+      _.flatten(_.map(prepped_rows, (row) => _.map(exp_years, (yr) => row[yr])))
```
Comment (ktw1016) [inline client/src/panels/panel_declarations/finances/transfer_payments/historical_g_and_c.js:196]: This can probably be written in `chain` like above
