### PR TITLE
hotfix for rpb displaytable column removal error

### LINKED ISSUE #620: DisplayTable in RPB, error on removal of sorted column
Worked this out from a prod error logged to analytics, so some urgency to fixing it!

Easy to reproduce:
  - go to the RPB and enable two columns of data
  - sort by one of the two
  - disable the currently sorted column
  - crash :(

### PR DESCRIPTION
**Pull request by ktw1016**
fixes #620

### CODE REVIEW

File: client/src/components/DisplayTable.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ export class DisplayTable extends React.Component {
       */,
     } = this.props;
     const { sort_by, descending, searches } = this.state;
-
+    console.log(column_configs);
```
Comment (Stephen-ONeil) [inline client/src/components/DisplayTable.js:74]: Stray `console.log`

File: client/src/components/DisplayTable.js [hunk 2]
```diff
@@ -111,7 +111,7 @@ export class DisplayTable extends React.Component {
           .value()
       )
       .thru((unsorted_array) => {
-        if (sort_by) {
+        if (col_configs_with_defaults[sort_by]) {
```
Comment (Stephen-ONeil) [inline client/src/components/DisplayTable.js:114]: Could also be `_.has(col_configs_with_defaults, sort_by)`. In this case, I think they're equivalent, just pointing out because using `_.has` to check existence of a key on an object can be useful in other cases (e.g. if the value of the key itself might be falsey, but all you care about is if the object has the key). Maybe worth using here just because it is a better representation of that the check actually cares about (the existence of the column, not the value of the config).
