### PR TITLE
Handle broken infograph links

### LINKED ISSUE #443: More gracefully handle traffic to dead infographics
In particular, a fair number of users have been trying to visit infographics for programs and CRSOs that fell out of our window recently. Currently, trying to route to one gets you an error page. 

A better behaviour would be to, for example, fall back to the parent department (or home page?) with a banner explaining why you can't visit the page you were linked to.

Easiest approach would be to bail back home on any failing infographic route. I don't like this because it could hide actual bugs down the road.

Best, but probably the most involved, approach would be to keep a list of recently dead subject ids and their appropriate fallback subjects. Then we'd have something to check against whenever an infographic route fails to match any of the current subjects. On the other hand, that would be a new dataset for the pipeline to produce and yet another thing to maintain. Would it be worth the effort?

### LINKED ISSUE #822: Handle broken links better
If the panel part of the link is broken, just direct them to whatever infographic page it should be

If the whole thing is broken, just redirect them to #home

Maybe a banner to let them know they were redirected because link is broken

### PR DESCRIPTION
**Pull request by ktw1016**
closes #822 
closes #443 

Errors to try:
#orgs/ERROR/1/infograph/financial
#orgs/program/AGR-ERROR/infograph/financial
#orgs/crso/FO-ERROR/infograph/financial
#orgs/dept/ERROR/infograph/financial
#orgs/dept/1/infograph/financial/.-ERROR.-(panel_key.-.-'welcome_mat)
#orgs/dept/1/infograph/ERROR

### CODE REVIEW

File: client/src/core/ErrorBoundary.js [hunk 1]
```diff
@@ -1,126 +1,199 @@
...
-    this.setState({
-      testing_for_stale_client: false,
-    });
+      if (_.isNull(error)) {
+        return this.props.children;
+      }
+      if (testing_for_stale_client) {
+        this.catch_stale_client_error_case();
+        return null;
+      } else {
```
Comment (ktw1016) [inline client/src/core/ErrorBoundary.js:94]: For ease of reading, the meaningful part that changed start here

File: client/src/core/ErrorBoundary.js [hunk 2]
```diff
@@ -1,126 +1,199 @@
...
+            });
+          } else {
+            // subject doesn't exist, redirect to home
+            window.location.replace("#home");
+            window.location.reload();
+          }
+        } else if (infograph_regex_without_panel) {
+          // Without panel part, url will only fail with subject not matching
+          window.location.replace("#home");
+          window.location.reload();
```
Comment (ktw1016) [inline client/src/core/ErrorBoundary.js:139]: to here

File: client/src/core/ErrorBoundary.js [hunk 3]
```diff
@@ -1,126 +1,230 @@
...
+      } else {
+        const redirect_to_parent_dept_or_home = (level, subj_id) => {
+          const parent_dept_code = _.split(subj_id, "-")[0];
+          const parent_dept = Dept.lookup(parent_dept_code);
+          if ((level === "program" || level === "crso") && parent_dept) {
+            set_redirect_msg(
+              `The ${trivial_text_maker(
+                level
+              )} you tried to visit is either dead or invalid. We redirected you to its parent department.`
+            );
```
Comment (ktw1016) [inline client/src/core/ErrorBoundary.js:105]: Obviously all of this redirect text can be improved, and also we could possibly redirect to `related` instead of `intro` for this case

File: client/src/InfoBase/App.js [hunk 4]
```diff
@@ -118,15 +118,11 @@ export class App extends React.Component {
   }
 
   state = {
-    showNotification: false,
-    message: "",
+    show_redirected_msg: sessionStorage.getItem("redirected_msg"),
```
Comment (Stephen-ONeil) [inline client/src/InfoBase/App.js:121]: Ooh, instead of `sessionStorage`, this could finally be a good reason to make use of the app-wide provider. Would deal with that old `No reducer provided for key "app"` error message in the process, haha.

File: client/src/core/ErrorBoundary.js [hunk 5]
```diff
@@ -1,126 +1,230 @@
...
-      testing_for_stale_client: false,
-    });
+      if (_.isNull(error)) {
+        return children;
+      }
+      if (testing_for_stale_client) {
+        this.catch_stale_client_error_case();
+        return null;
+      } else {
+        const redirect_to_parent_dept_or_home = (level, subj_id) => {
```
Comment (Stephen-ONeil) [inline client/src/core/ErrorBoundary.js:97]: I think all the infographic redirect stuff should live in the infographic route rather than the `ErrorBoundary`. Would prefer to only try and handle generic/app-wide errors at this level.

Comment (Stephen-ONeil) [reply client/src/core/ErrorBoundary.js:97]: If we want sub-app specific redirect rules in other places, maybe it could be a configurable part of the `StandardRouteContainer` or it's own higher order component for wrapping routes in.

File: client/src/core/ErrorBoundary.js [hunk 6]
```diff
@@ -1,126 +1,230 @@
...
+            set_redirect_msg(
+              "The organization you tried to visit is invalid. We redirected you to homepage."
+            );
+            window.location.replace("#home");
+          }
+          window.location.reload();
+        };
+        const current_url = location.pathname;
+        const regex_template =
+          "orgs/(gov|dept|program|tag|crso)/(.*)/infograph/(.*)";
```
Comment (Stephen-ONeil) [inline client/src/core/ErrorBoundary.js:119]: Using `withRouter`, isn't the parsed URL available in the `props`?

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Couple comments, suggesting a bit of reorganizing

Seems to be working well though, nice!

File: client/src/InfoBase/App.js (hunk 4 above)
Comment (ktw1016) [reply client/src/InfoBase/App.js:121]: Well, with how it is now, it'll need to keep its variables on reload, and I don't think redux storage will keep that! (Although if we do this at Infographic level, then maybe we can use react router dom and it might have some redirect stuff that doesn't reload? I'd have to try that out)

Comment (Stephen-ONeil) [reply client/src/InfoBase/App.js:121]: Ah, hmm, yeah. Just need to catch the error inside the route rather than let it hit the error boundary and junk everything up 👍

File: client/src/core/ErrorBoundary.js (hunk 6 above)
Comment (ktw1016) [reply client/src/core/ErrorBoundary.js:119]: Yeah, I'm using that just above `location.pathname`. `regex_template` is the regex to run against the url. Hmm, am I missing something here?

Comment (Stephen-ONeil) [reply client/src/core/ErrorBoundary.js:119]: `match`, https://reactrouter.com/core/api/match

E.g. `const { match: {
    params: { level, subject_id, active_bubble_id, options },
  }} = this.props;`

Comment (Stephen-ONeil) [reply client/src/core/ErrorBoundary.js:119]: Where `level`, `subject_id`, etc. are the parameter names from the URL path definition
```
<Route
  path="/orgs/:level/:subject_id/infograph/:active_bubble_id?/:options?/"
  component={Infographic}
/>
```

File: client/src/infographic/Infographic.js [hunk 7]
```diff
@@ -351,17 +352,76 @@ class InfoGraph_ extends React.Component {
...
+      set_redirect_msg(
+        "The organization you tried to visit is invalid. We redirected you to homepage."
+      );
+      window.location.replace("#home");
+    }
+    window.location.reload();
+  } else if (!bubble_id) {
+    redirect_to_intro(subject);
+  } else if (options) {
+    (() => {
```
Comment (GarvinH) [inline client/src/infographic/Infographic.js:403]: I think we can remove the anonymous function now and execute the try block directly?

**Comment by ktw1016** [comment]
So I've been trying to use app wide redux store instead of session storage, and use `<Redirect/>`. The main problem of it was that it was trying to update redux state, and also return `<Redirect/>` at the same time. So what happened was that it redirects correctly, but gives error that react can't update state, and banner never shows up (from redux store)

I've tried few different ways to set redirect banner in componentdidmount, or do redirect in componentdidupdate, or use redux-thunk (to make a callback to dispatch). But nothing really worked out. If anyone knows how to solve it, please enlighten me!

File: client/src/core/ErrorBoundary.js (hunk 6 above)
Comment (ktw1016) [reply client/src/core/ErrorBoundary.js]: Oh yup you're right. As it moved to Infographic level, it's using it now

**Comment by Stephen-ONeil** [comment]
Using `<Redirect/>` within `Infographic.js`, right? What if what you stored in global state was both the redirect banner content and and the redirect target? Then `App.js` (or some HoC inside it, like the error boundary) could react to the global state change by redirecting and showing the banner (maybe break that in to two steps if necessary). That'd straighten it out, right?

File: client/src/infographic/Infographic.js [hunk 8]
```diff
@@ -350,56 +352,127 @@ class InfoGraph_ extends React.Component {
...
+        params: { level, subject_id, active_bubble_id, options },
+      },
+      set_redirect,
+    } = this.props;
+
+    const is_level_valid = _.chain(Subject).keys().includes(level).value();
+    if (!is_level_valid) {
+      set_redirect(
+        "home",
+        "The level of organization you tried to visit is invalid. We redirected you to homepage."
```
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.js:370]: Needs translation

File: client/src/core/ErrorBoundary.js [hunk 9]
```diff
@@ -61,10 +63,12 @@ export class ErrorBoundary extends React.Component {
     throw this.state.error;
   }
   render() {
+    const { children } = this.props;
     const { error, testing_for_stale_client } = this.state;
+    const redirected_msg = sessionStorage.getItem("redirected_msg");
```
Comment (Stephen-ONeil) [inline client/src/core/ErrorBoundary.js:68]: Still using `sessionStorage` rather than app store? Here and two other places. Are those leftovers, or was some mix necessary in the end?

File: client/src/infographic/Infographic.js (hunk 8 above)
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.js:370]: Needs translation (here and a few other spots)

File: client/src/infographic/Infographic.js [hunk 10]
```diff
@@ -350,56 +352,127 @@ class InfoGraph_ extends React.Component {
...
+    const SubjectModel = Subject[level];
+    const subject = SubjectModel.lookup(subject_id);
+    const bubble_id = bubble_defs[active_bubble_id] ? active_bubble_id : null;
+
+    if (!subject) {
+      const parent_dept_code = _.split(subject_id, "-")[0];
+      const parent_dept = Dept.lookup(parent_dept_code);
+      if ((level === "program" || level === "crso") && parent_dept) {
+        set_redirect(
+          "orgs/dept/${parent_dept.id}/infograph/intro",
```
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.js:382]: Oops, "s instead of `s, haha

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Quick review on some small things. Almost good to go I think, I'll do one last quick look over after these are addressed.

File: client/src/infographic/Infographic.yaml [hunk 11]
```diff
@@ -61,6 +61,26 @@ infograph_explorer_link:
   en: Advanced search
   fr: Recherche avancée
 
+invalid_level_redirect_home:
+  transform: [handlebars]
+  en: The "{{level}}" is invalid. We redirected you to homepage.
+  fr: TODO
+invalid_subject_redirect_parent_dept:
+  transform: [handlebars]
+  en: The organization "{{subject_id}}" is invalid. We redirected you to its parent department.
```
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.yaml:70]: Your browser was attempting to visit one of our infographics. Unfortunately, we could not recognize "{{subject_id}}" as a valid infographic parameter. While "{{subject_id}}" itself couldn't be found, we were able to match the "{{dept_code}}" portion to a valid organization. We have redirected you to the infographic for that organization.

You were likely following a link intended to take you to an infographic for a core responsibility or program belonging to this organization. You can view and navigate to all of this organization's valid core responsibilities and programs under "Where can I go from here?" below.

If you believe something is incorrect on our end, we invite you to alert us using the Report a Problem form provided at the bottom of the page. Thank you!

File: client/src/infographic/Infographic.yaml [hunk 12]
```diff
@@ -61,6 +61,26 @@ infograph_explorer_link:
...
+  transform: [handlebars]
+  en: The organization "{{subject_id}}" is invalid. We redirected you to homepage.
+  fr: TODO
+invalid_panel:
+  transform: [handlebars]
+  en: The link to panel is invalid.
+  fr: TODO
+invalid_bubble_redirect_intro:
+  transform: [handlebars]
+  en: The "{{bubble_id}}" is invalid. We redirected you to intro page.
```
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.yaml:82]: This error case can probably fail quietly. I think it would be fair to just leave them in the infographic with no selected bubble if the bubble portion is malformed, wouldn't even need to redirect or anything.

File: client/src/infographic/Infographic.yaml [hunk 13]
```diff
@@ -61,6 +61,26 @@ infograph_explorer_link:
...
+  transform: [handlebars]
+  en: The organization "{{subject_id}}" is invalid. We redirected you to its parent department.
+  fr: TODO
+invalid_subject_redirect_home:
+  transform: [handlebars]
+  en: The organization "{{subject_id}}" is invalid. We redirected you to homepage.
+  fr: TODO
+invalid_panel:
+  transform: [handlebars]
+  en: The link to panel is invalid.
```
Comment (Stephen-ONeil) [inline client/src/infographic/Infographic.yaml:78]: This doesn't need to be a redirect thing, right? The `JSURL` parsing in `componentDidUpdate` should handle errors itself (and probably fail quietly).

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Misc comments, and tried my hand at writing text for the redirect banners. Might be a bit long in most cases though.

File: client/src/core/ErrorBoundary.js [hunk 14]
```diff
@@ -78,24 +83,47 @@ export class ErrorBoundary extends React.Component {
             alignItems: "center",
           }}
         >
+          {redirected_msg ? (
```
[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/core/ErrorBoundary.js:86]: This is kind of an artifact from when it was redirecting at error boundary level, but it's still applicable (sort of). Because `SafeJSURL.parse(options);` itself throws an error and hits the error boundary for a second before the reload happens.

Just left it in there to see the reaction since it was already written. I can remove it!

File: client/src/infographic/Infographic.yaml (hunk 12 above)
Comment (ktw1016) [reply client/src/infographic/Infographic.yaml:82]: okay sure

File: client/src/infographic/Infographic.yaml (hunk 13 above)
Comment (ktw1016) [reply client/src/infographic/Infographic.yaml:78]: Yes, if actual panel string is invalid. But if the whole structure is wrong, like `#orgs/gov/gov/infograph/financial/.-ERROR.-(panel_key.-.-'welcome_mat)`. It'll throw an error

File: client/src/infographic/Infographic.js [hunk 15]
```diff
@@ -358,10 +363,63 @@ const Infographic = ({
     params: { level, subject_id, active_bubble_id, options },
   },
 }) => {
+  const set_redirect_msg = (msg_key, args) => {
```
[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/infographic/Infographic.js:366]: Can you elaborate on what you mean by its own HoC? This doesn't render anything, so they're not really components. I did put replacing and reloading to here to centralize it now tho.

I could put all of this redirect code in a separate function, although checking for level have to happen before getting the subject, so then I'd need two different functions, which could be a bit messy in its own. Although that might look clearer in the bigger picture

[the remark this answers is not in the document]
Comment (Stephen-ONeil) [reply client/src/infographic/Infographic.js]: Ahh, haha, know what? I was confused by the GitHub diff/not reading carefully.

image


Didn't notice the jump in line number, thought this was all inside the `AnalyticsSynchronizer` component for some reason, which would have been a weird place for it. You can ignore this one!

File: client/src/infographic/Infographic.yaml (hunk 13 above)
Comment (Stephen-ONeil) [reply client/src/infographic/Infographic.yaml:84]: I meant the actual errors thrown by `JSURL` on unparsable URLs, yeah. If those options can't be parsed, we don't actually know if they were a `panel_key` or something else (we use them for like linking to indicator modals too, and generally the idea was that panels could use them for arbitrary state if that ever became necessary). Figure those errors should just be suppressed (and maybe logged to analytics), but don't really need to be communicated up to the user.

File: client/src/core/ErrorBoundary.js (hunk 14 above)
[the remark this answers is not in the document]
Comment (Stephen-ONeil) [reply client/src/core/ErrorBoundary.js]: Do you mean an error in the `ErrorBoundary` itself, or in the redirect code? The `ErrorBoundary` itself is tested by the route load tests. We could add specific testcafe tests for the redirect code too, would be pretty easy.

[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/core/ErrorBoundary.js:86]: Well, since I just removed SafeJSURL parse, I removed this as well. I guess when it gets stuck reloading, we'll put this back in haha

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
Still think the redirect code should be moved out of the error boundary. Other than that, just finishing the text (team feedback and translation)!

**Comment by Stephen-ONeil** [comment]
Ah, haha, you cleaned up the `ErrorBoundary` while I was writing that. Ok, just text left then!

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]

File: client/src/infographic/Infographic.yaml [hunk 16]
```diff
@@ -61,6 +61,34 @@ infograph_explorer_link:
...
+invalid_redirect_home:
+  transform: [handlebars]
+  en: |
+    Your browser was attempting to visit one of our infographics. Unfortunately, we could not recognize "{{param}}" as a valid infographic parameter. You have been redirected to the GC InfoBase home page.
+
+    If you know the subject of the infographic you intended to view (e.g. the organization or program name), please try finding it using our search bar below.
+
+    If you believe something is incorrect on our end, we invite you to alert us using the Report a Problem form provided at the bottom of the page. Thank you!
+  fr: |
+    Votre navigateur a tenté de visiter l'une de nos infographies. Malheureusement, nous n'avons pas pu reconnaître "{{param}}" en tant que paramètre infographique valide. Vous avez été redirigé vers la page d'accueil l'InfoBase du GC.
```
[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/infographic/Infographic.yaml:73]: This is from Andre

[the remark this answers is not in the document]
Comment (Stephen-ONeil) [reply client/src/infographic/Infographic.yaml:73]: Ahh, ok, sorry!

File: client/src/InfoBase/App.js [hunk 17]
```diff
@@ -169,10 +169,27 @@ export class App extends React.Component {
...
+                  text_maker("common_redirect_msg", {
+                    url: get_session_storage_w_expiry("pre_redirected_url"),
+                  }),
+                  get_session_storage_w_expiry("redirected_msg"),
+                ]}
+                hideNotification={() => {
+                  sessionStorage.removeItem("pre_redirected_url");
+                  sessionStorage.removeItem("redirected_msg");
+                  this.setState({ show_redirected_msg: false });
+                }}
```
[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/InfoBase/App.js:192]: Can you elaborate on what you mean by separate components, do you mean this should use a different alert component from outage?

This is not exactly "redirect component", it's just used to alert user on the error. The actual "redirect" is happening in Infographics level, so I think it should do the logging there

File: client/src/infographic/Infographic.js [hunk 18]
```diff
@@ -148,7 +153,19 @@ class InfoGraph_ extends React.Component {
...
         reset_scroll();
       }
-      const options = SafeJSURL.parse(this.props.options);
+      const options = (() => {
+        try {
+          return SafeJSURL.parse(this.props.options);
+        } catch {
+          log_standard_event({
+            SUBAPP: window.location.hash.replace("#", ""),
+            MISC1: "ERROR_IN_JSURL_PARSE",
```
[the remark this answers is not in the document]
Comment (ktw1016) [reply client/src/infographic/Infographic.js:162]: Agreed to put them as warnings for weekly reports on that, should be separate from this PR though

[the remark this answers is not in the document]
Comment (Stephen-ONeil) [reply client/src/infographic/Infographic.js:162]: Agreed, that's why I opened the issue. Was just linking it to this because it's where I had the thought 👍

File: client/src/InfoBase/App.js (hunk 17 above)
[the remark this answers is not in the document]
Comment (Stephen-ONeil) [reply client/src/InfoBase/App.js:192]: Oops, sorry for not getting back on this.

I meant more as a code organization/clean up thing. We're ending up with a lot of functionality directly embedded in the `App` component. I was suggesting these headers should be encapsulated as their own components and moved to their own modules in `src/core/` (for now, some day we'll reorganize the directory structure). Like `InsertRuntimeFooterLinks` etc.

The module for the `RedirectHeader` (or whatever) component could also export a function like `redirect_with_message` or something, with equivalent behaviour to the `set_redirect_msg` function currently in `Infographic.js`. Right now implementation details for this feature are split between `App.js` and `Infographic.js`, which a) makes it harder to maintain, and b) makes it harder\* to reuse elsewhere if needed.

\* _could_ use the redirect header from anywhere right now, I guess, but you'd need to understand (or copy) the implementation details from `Infographic.js`, which would just make maintenance and even bigger nightmare.

**Review by Stephen-ONeil — CHANGES_REQUESTED** [review]
https://github.com/TBS-EACPD/infobase/pull/826#discussion_r551588660

**Review by Stephen-ONeil — APPROVED** [review]
👍
