### PR TITLE
Fix infographic links in flat results tables

### LINKED ISSUE #275: Results table program links broken

### PR DESCRIPTION
**Pull request by cookkate**
Fixes #275

### CODE REVIEW

File: client/src/panels/result_graphs/result_flat_table.js [hunk 1]
```diff
@@ -89,7 +90,7 @@ const subject_link = (subject) => {
   } else {
     return (
       <span>
-        <a href={infograph_href_template(subject,"results")}>
+        <a href={infograph_href_template(subject.data.subject,"results")}>
```
Comment (Stephen-ONeil) [inline client/src/panels/result_graphs/result_flat_table.js]: Oh, ok, so `ind.parent_subject` passed as the `subject` argument isn't a subject, it's a list (or flattened hierarchy?) node containing a subject. If I've got that right, some renaming could help make sense of things.
