### PR TITLE
Fix nivo bubble

### LINKED ISSUE #724: Broken Circle Nivo
related to #599 

image

### PR DESCRIPTION
**Pull request by GarvinH**
closes #724 

image

### CODE REVIEW

File: client/src/charts/wrapped_nivo/CircleProportionChart.js [hunk 1]
```diff
@@ -115,16 +115,19 @@ export class CircleProportionChart extends React.Component {
       // so we need to remove the inner portion from the total here
       value: parent_value - child_value,
       color: color_scale(parent_name),
```
Comment (ktw1016) [inline client/src/charts/wrapped_nivo/CircleProportionChart.js:117]:
```
      children: child_value
        ? [
            {
              id: child_name,
              name: child_name,
              value: child_value,
              color: color_scale(child_name),
            },
          ]
        : 0,
```
I think you can do it like this?
